server:
  port: 9003
spring:
  application:
    name: API-GATEWAY-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mariadb://localhost:3306/jwt_security #database name here: eg. jdbc:mariadb://localhost:3306/postbank_sacco
    username: root  #database username here
    password: FRANKMUGAH97 #database password here
    driverClassName: org.mariadb.jdbc.Driver
    dbname: #database name here

